version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/futurist.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

  signals_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/signals.log
    maxBytes: 52428800  # 50MB
    backupCount: 10

loggers:
  "":  # root logger
    level: INFO
    handlers: [console, file]
    propagate: false

  crawler:
    level: DEBUG
    handlers: [console, file, signals_file]
    propagate: false

  processor:
    level: DEBUG
    handlers: [console, file, signals_file]
    propagate: false

  analyzer:
    level: DEBUG
    handlers: [console, file, signals_file]
    propagate: false

  api:
    level: INFO
    handlers: [console, file]
    propagate: false

  error:
    level: ERROR
    handlers: [console, error_file]
    propagate: false